-- EventPulse v1 schema
-- Decisions:
--   - UUID primary keys, generated by Postgres (gen_random_uuid via pgcrypto).
--   - Self-referencing interests tree (sport > league > team).
--   - Join tables for many-to-many (event_interests, feed_item_interests).
--   - JSONB for source-specific metadata (scores, posters, teams, etc.).
--   - All timestamps TIMESTAMPTZ stored in UTC.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email           TEXT        NOT NULL UNIQUE,
    display_name    TEXT,
    oauth_provider  TEXT        NOT NULL,
    oauth_subject   TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ,
    CONSTRAINT users_oauth_unique UNIQUE (oauth_provider, oauth_subject)
);

-- ---------------------------------------------------------------------------
-- Interest taxonomy (self-referencing tree: sport > league > team)
-- ---------------------------------------------------------------------------
CREATE TABLE interests (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug          TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL,
    category      TEXT NOT NULL,
    parent_id     UUID REFERENCES interests(id) ON DELETE SET NULL
);

CREATE INDEX idx_interests_parent_id ON interests(parent_id);
CREATE INDEX idx_interests_category  ON interests(category);

CREATE TABLE user_interests (
    user_id     UUID NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    interest_id UUID NOT NULL REFERENCES interests(id) ON DELETE CASCADE,
    weight      REAL NOT NULL DEFAULT 1.0,
    PRIMARY KEY (user_id, interest_id)
);

CREATE INDEX idx_user_interests_interest_id ON user_interests(interest_id);

-- ---------------------------------------------------------------------------
-- Events (the moat: real-world things that bias ranking)
-- ---------------------------------------------------------------------------
CREATE TABLE events (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    title       TEXT        NOT NULL,
    category    TEXT        NOT NULL,
    starts_at   TIMESTAMPTZ NOT NULL,
    ends_at     TIMESTAMPTZ,
    status      TEXT        NOT NULL,
    source      TEXT        NOT NULL,
    source_id   TEXT        NOT NULL,
    metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT events_source_unique UNIQUE (source, source_id),
    CONSTRAINT events_status_check  CHECK (status IN ('upcoming', 'live', 'recent'))
);

CREATE INDEX idx_events_status_starts_at ON events(status, starts_at);
CREATE INDEX idx_events_starts_at        ON events(starts_at);

CREATE TABLE event_interests (
    event_id    UUID NOT NULL REFERENCES events(id)    ON DELETE CASCADE,
    interest_id UUID NOT NULL REFERENCES interests(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, interest_id)
);

CREATE INDEX idx_event_interests_interest_id ON event_interests(interest_id);

-- ---------------------------------------------------------------------------
-- Topic aliases: how each interest maps to source-specific search terms.
-- e.g. interest 'ipl' -> reddit:'r/cricket', bluesky:'#IPL2026', hn:'IPL'
-- ---------------------------------------------------------------------------
CREATE TABLE topic_aliases (
    interest_id UUID NOT NULL REFERENCES interests(id) ON DELETE CASCADE,
    source      TEXT NOT NULL,
    query       TEXT NOT NULL,
    PRIMARY KEY (interest_id, source, query)
);

CREATE INDEX idx_topic_aliases_source ON topic_aliases(source);

-- ---------------------------------------------------------------------------
-- Feed items: cached aggregated content from external sources.
-- ---------------------------------------------------------------------------
CREATE TABLE feed_items (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    source            TEXT        NOT NULL,
    source_id         TEXT        NOT NULL,
    url               TEXT        NOT NULL,
    title             TEXT        NOT NULL,
    thumbnail_url     TEXT,
    published_at      TIMESTAMPTZ,
    related_event_id  UUID        REFERENCES events(id) ON DELETE SET NULL,
    metadata          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    fetched_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT feed_items_source_unique UNIQUE (source, source_id)
);

CREATE INDEX idx_feed_items_published_at      ON feed_items(published_at DESC);
CREATE INDEX idx_feed_items_source            ON feed_items(source);
CREATE INDEX idx_feed_items_related_event_id  ON feed_items(related_event_id);

CREATE TABLE feed_item_interests (
    feed_item_id UUID NOT NULL REFERENCES feed_items(id) ON DELETE CASCADE,
    interest_id  UUID NOT NULL REFERENCES interests(id)  ON DELETE CASCADE,
    PRIMARY KEY (feed_item_id, interest_id)
);

CREATE INDEX idx_feed_item_interests_interest_id ON feed_item_interests(interest_id);

-- ---------------------------------------------------------------------------
-- Engagement (used later for personalization)
-- ---------------------------------------------------------------------------
CREATE TABLE user_engagement (
    user_id      UUID        NOT NULL REFERENCES users(id)       ON DELETE CASCADE,
    feed_item_id UUID        NOT NULL REFERENCES feed_items(id)  ON DELETE CASCADE,
    action       TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, feed_item_id, action),
    CONSTRAINT user_engagement_action_check CHECK (action IN ('view', 'click', 'save', 'hide'))
);

CREATE INDEX idx_user_engagement_user_id_created_at ON user_engagement(user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- AI summaries per event (regenerated daily for ongoing events)
-- ---------------------------------------------------------------------------
CREATE TABLE event_summaries (
    event_id      UUID        PRIMARY KEY REFERENCES events(id) ON DELETE CASCADE,
    summary       TEXT        NOT NULL,
    model         TEXT        NOT NULL,
    generated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
